Repository wecode-bootcamp-korea/39-1st-HealthEat-frontend, pull requests merged in 2022-11, with the labels that each got.

#1 [39기 우석민] ADD: Nav 수정완료하였습니다.
  public/images/free-icon-add-cart-6032906.png
  public/images/free-icon-user-1077063.png
  src/Router.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/ProductDetail/ProductDetail.js
Labels: 멘토 리뷰 요청

#7 [39기 우석민] ADD:Nav 수정하였습니다.
  src/components/Nav/Nav.scss
Labels: 멘토 리뷰 요청

#9 ADD: Nav 로고 링크 수정 완료
  src/components/Nav/Nav.js
Labels: 멘토 리뷰 요청

#4 [39기 이상윤] Refactor: 이미지 변경 완료 & 슬라이드 크기 수정 & 메뉴 아이콘 링크 연결 (Main 페이지 작업 완료 ✅)
  README.md
  package-lock.json
  package.json
  public/data/sliderData.json
  public/images/mainListIcons/articulation.png
  public/images/mainListIcons/diet-food.png
  public/images/mainListIcons/energy-drink.png
  public/images/mainListIcons/eye-care.png
  public/images/mainListIcons/intestine.png
  public/images/mainListIcons/liver.png
  public/images/mainListIcons/skin-care.png
  public/images/mainListIcons/stomach.png
  public/images/mainPromotionSlideImages/diana-polekhina-v0ZjnfxnP60-unsplash.jpg
  public/images/mainPromotionSlideImages/leohoho-DRchVK5apjw-unsplash.jpg
  public/images/mainPromotionSlideImages/supliful-571ysEZSMFU-unsplash.jpg
  src/index.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/MenuList/ListItem/ListItem.js
  src/pages/Main/MenuList/MenuList.js
  src/pages/Main/PromotionSlide/PromotionSlide.js
  src/pages/ProductDetail/Detail.js
  src/pages/ProductDetail/Detail.scss
Labels: 멘토 리뷰 요청

#10 [39기 이상윤] ADD: productDetail 페이지 레이아웃 구현 + 데이터 통신 완료
  public/data/ProductDetail.json
  src/components/Nav/Nav.js
  src/pages/ProductDetail/BuyBar/BuyBar.js
  src/pages/ProductDetail/ProductDemonstration/ProductDemonstration.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
Labels: 멘토 리뷰 요청

#5 [39기 이혜원] Add: 로그인 페이지 레이아웃 작업 중
  public/data/sample.json
  public/images/pill.png
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
Labels: 수정 요청, 추가 기능 구현 중

#8 [39기 이혜원] Add: 회원가입 페이지 레이아웃 작업 중
  public/data/sample.json
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
Labels: Conflict 해결 요청, 추가 기능 구현 중
